-- Rollback Migration for RLS Policies
-- This migration removes all RLS policies and helper functions

-- Drop the trigger for new user registration
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Drop helper functions
DROP FUNCTION IF EXISTS handle_new_user();
DROP FUNCTION IF EXISTS has_any_role(user_role[]);
DROP FUNCTION IF EXISTS has_role(user_role);
DROP FUNCTION IF EXISTS is_admin();
DROP FUNCTION IF EXISTS get_user_role();

-- Disable RLS on all tables
ALTER TABLE IF EXISTS user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS raw_materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS material_intake_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS production_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS batch_inputs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pricing_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS interaction_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS samples_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS returns_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS credit_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS financial_ledger DISABLE ROW LEVEL SECURITY;